# Generated by Django 6.0.4 on 2026-05-06 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilSysVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philSys_number', models.CharField(blank=True, max_length=12, null=True)),
                ('philSys_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_method', models.CharField(choices=[('qr', 'QR Code'), ('psn', 'PSN'), ('biometric', 'Biometric')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_payload', models.JSONField(blank=True, help_text='Raw API response for audit purposes', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='philsys_attempts', to='residents.resident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='philsys_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhilSys Verification Attempt',
                'verbose_name_plural': 'PhilSys Verification Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='philsys_phi_created_73f2f5_idx'), models.Index(fields=['status'], name='philsys_phi_status_d3aab6_idx'), models.Index(fields=['user', '-created_at'], name='philsys_phi_user_id_69cd4c_idx')],
            },
        ),
    ]
