# Generated by Django 6.0.2 on 2026-02-22 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(default='Barangay Sample', max_length=200)),
                ('municipality', models.CharField(default='Municipality of Sample', max_length=200)),
                ('province', models.CharField(default='Province of Sample', max_length=200)),
                ('region', models.CharField(default='Region Sample', max_length=200)),
                ('barangay_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('captain_name', models.CharField(blank=True, max_length=200)),
                ('secretary_name', models.CharField(blank=True, max_length=200)),
                ('treasurer_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
