# Generated by Django 6.0.2 on 2026-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_philsys_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='philSys_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='philsys_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('captain', 'Barangay Captain'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('kagawad', 'Kagawad'), ('sk_chairperson', 'SK Chairperson'), ('lupong_member', 'Lupon Member'), ('resident', 'Resident'), ('admin', 'Administrator'), ('staff', 'Staff')], default='resident', max_length=20),
        ),
    ]
