# Generated by Django 4.2.21 on 2026-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fingerprint_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
