# Generated by Django 6.0.2 on 2026-04-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_fingerprint_template'),
        ('residents', '0004_resident_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resident',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='residents.resident'),
        ),
    ]
