# Generated by Django 6.0.2 on 2026-04-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='captain_name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='secretary_name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='treasurer_name',
        ),
    ]
