# Generated by Django 6.0.2 on 2026-04-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_systemsettings_captain_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fingerprint_template',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_philsys_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='philSys_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='philsys_verified_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
