# Generated by Django 6.0.4 on 2026-05-06 15:49

import django.db.models.deletion
import residents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Purok',
                'verbose_name_plural': 'Puroks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResidentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=residents.models.generate_reference_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(default='single', max_length=20)),
                ('nationality', models.CharField(default='Filipino', max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('highest_education', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('house_number', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('purok', models.CharField(blank=True, max_length=100)),
                ('barangay', models.CharField(default='Sample Barangay', max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='Cagayan de Oro', max_length=100)),
                ('zip_code', models.CharField(default='9000', max_length=10)),
                ('years_of_residency', models.IntegerField(default=0)),
                ('philSys_number', models.CharField(blank=True, max_length=12, null=True)),
                ('is_joining_household', models.BooleanField(default=False)),
                ('household_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_4ps_member', models.BooleanField(default=False)),
                ('is_sole_parent', models.BooleanField(default=False)),
                ('is_registered_voter', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='registrations/photos/')),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='registrations/ids/')),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='registrations/birth_certs/')),
                ('proof_of_residency', models.ImageField(blank=True, null=True, upload_to='registrations/residency/')),
                ('data_privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resident Registration',
                'verbose_name_plural': 'Resident Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='residents.purok')),
            ],
            options={
                'ordering': ['household_no'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced')], default='single', max_length=20)),
                ('nationality', models.CharField(default='Filipino', max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('is_household_head', models.BooleanField(default=False)),
                ('philSys_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='PhilSys Number (PSN)')),
                ('philSys_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='PhilSys Card Number (PCN)')),
                ('is_philsys_verified', models.BooleanField(default=False)),
                ('philsys_verified_at', models.DateTimeField(blank=True, null=True)),
                ('philsys_verification_method', models.CharField(blank=True, choices=[('qr', 'QR Code'), ('psn', 'PSN'), ('biometric', 'Biometric')], max_length=20, null=True)),
                ('is_registered_voter', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False, verbose_name='Person with Disability')),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_4ps_member', models.BooleanField(default=False, verbose_name='4Ps Member')),
                ('is_indigent', models.BooleanField(default=False)),
                ('is_solo_parent', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=False, verbose_name='Barangay Functionary')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents/photos/')),
                ('fingerprint_template', models.TextField(blank=True, help_text='Base64 encoded fingerprint template', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='residents.household')),
                ('purok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='residents.purok')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
