# Generated by Django 6.0.4 on 2026-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resident',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'suffix', 'birthdate'), name='unique_resident_name_birthdate'),
        ),
    ]
