# Generated by Django 6.0.2 on 2026-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_philsys_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='philSys_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PhilSys Card Number (PCN)'),
        ),
        migrations.AddField(
            model_name='resident',
            name='philSys_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='PhilSys Number (PSN)'),
        ),
        migrations.AddField(
            model_name='resident',
            name='philsys_verification_method',
            field=models.CharField(blank=True, choices=[('qr', 'QR Code'), ('psn', 'PSN'), ('biometric', 'Biometric')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='philsys_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
