# Generated by Django 4.2.21 on 2026-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_unique_resident_name_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='fingerprint_slot',
            field=models.IntegerField(blank=True, help_text='Hardware memory slot ID (e.g. 1-1000)', null=True),
        ),
    ]
