# Generated by Django 6.0.4 on 2026-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_add_payment_flags'),
    ]

    def nullify_biometrics(apps, schema_editor):
        Resident = apps.get_model('residents', 'Resident')
        Resident.objects.all().update(fingerprint_template=None)

    operations = [
        migrations.RunPython(nullify_biometrics),
    ]
