# Generated by Django 4.2.21 on 2026-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_resident_fingerprint_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='fingerprint_slot',
        ),
        migrations.AddField(
            model_name='resident',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, help_text='Slot ID in the R307 sensor (1-1000)', null=True, unique=True),
        ),
    ]
