# Generated by Django 4.2.21 on 2026-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_resident_fingerprint_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Barangay Functionary'),
        ),
    ]
