# Generated by Django 6.0.2 on 2026-04-28 11:12

import residents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_resident_is_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=residents.models.generate_reference_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('civil_status', models.CharField(default='single', max_length=20)),
                ('nationality', models.CharField(default='Filipino', max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('highest_education', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('house_number', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('purok', models.CharField(blank=True, max_length=100)),
                ('barangay', models.CharField(default='Sample Barangay', max_length=100)),
                ('city', models.CharField(default='Cagayan de Oro', max_length=100)),
                ('zip_code', models.CharField(default='9000', max_length=10)),
                ('years_of_residency', models.IntegerField(default=0)),
                ('philSys_number', models.CharField(blank=True, max_length=12, null=True)),
                ('is_joining_household', models.BooleanField(default=False)),
                ('household_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_4ps_member', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='registrations/photos/')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='registrations/ids/')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='registrations/ids/')),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='registrations/birth_certs/')),
                ('proof_of_residency', models.ImageField(blank=True, null=True, upload_to='registrations/residency/')),
                ('data_privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resident Registration',
                'verbose_name_plural': 'Resident Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
