# Generated by Django 4.2.21 on 2026-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_remove_resident_fingerprint_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, help_text='0-based template page index in the R307/AS608 module (0 .. capacity-1)', null=True, unique=True),
        ),
    ]
