# Generated by Django 4.2.21 on 2026-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_alter_resident_fingerprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
