# Generated by Django 6.0.2 on 2026-04-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_residentregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentregistration',
            old_name='id_card_back',
            new_name='id_card',
        ),
        migrations.RemoveField(
            model_name='residentregistration',
            name='id_card_front',
        ),
        migrations.AddField(
            model_name='residentregistration',
            name='is_sole_parent',
            field=models.BooleanField(default=False),
        ),
    ]
