# Generated by Django 6.0.2 on 2026-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_rename_id_card_back_residentregistration_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentregistration',
            name='municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
