# Generated by Django 4.2.21 on 2026-05-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_household_latitude_household_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='household',
            name='longitude',
        ),
        migrations.AddField(
            model_name='purok',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purok',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
