# Generated by Django 6.0.2 on 2026-04-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_residentregistration_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentregistration',
            name='is_registered_voter',
            field=models.BooleanField(default=False),
        ),
    ]
