# Generated by Django 4.2.21 on 2026-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_remove_household_latitude_remove_household_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
