# Generated by Django 4.2.21 on 2026-06-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_household_latitude_household_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='household_relationship',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('grandchild', 'Grandchild'), ('grandparent', 'Grandparent'), ('other', 'Other Relative')], max_length=20, null=True, verbose_name='Relationship to Head'),
        ),
    ]
