# Generated by Django 4.2.21 on 2026-06-02 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_resident_household_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='parent_member',
            field=models.ForeignKey(blank=True, help_text='Custom parent relationship for interactive family tree', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_members', to='residents.resident'),
        ),
    ]
