# Generated by Django 6.0.4 on 2026-05-06 15:49

import certifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('child_name', models.CharField(blank=True, max_length=200)),
                ('child_birth_date', models.DateField(blank=True, null=True)),
                ('child_birth_place', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-date_issued', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_number', models.CharField(max_length=50, unique=True, verbose_name='CTC Number')),
                ('taxpayer_type', models.CharField(choices=[('individual', 'Individual'), ('corporation', 'Corporation')], default='individual', max_length=20)),
                ('place_of_issue', models.CharField(max_length=200)),
                ('height', models.CharField(blank=True, help_text='e.g. 170 cm', max_length=20)),
                ('weight', models.CharField(blank=True, help_text='e.g. 65 kg', max_length=20)),
                ('raw_taxable_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Property Value')),
                ('raw_taxable_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Gross Receipts')),
                ('raw_taxable_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Annual Income')),
                ('basic_tax', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('additional_tax_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Property)')),
                ('additional_tax_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Business)')),
                ('additional_tax_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Income)')),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_details', to='certifications.certificate')),
            ],
            options={
                'verbose_name': 'Cedula',
                'verbose_name_plural': 'Cedulas',
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=certifications.models.generate_tracking_code, max_length=20, unique=True)),
                ('cert_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('good_moral', 'Good Moral Certificate'), ('business_permit', 'Business Permit/Clearance'), ('comelec', 'COMELEC Certificate'), ('cedula', 'Community Tax Certificate'), ('late_registration', 'Certificate of Late Registration')], max_length=30)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('taxpayer_type', models.CharField(blank=True, max_length=20)),
                ('place_of_issue', models.CharField(blank=True, max_length=200)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('raw_taxable_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('raw_taxable_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('raw_taxable_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('child_name', models.CharField(blank=True, max_length=200)),
                ('child_birth_date', models.DateField(blank=True, null=True)),
                ('child_birth_place', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Admin notes (shown to resident on rejection)')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_request', to='payments.payment')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cert_requests', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Certificate Request',
                'verbose_name_plural': 'Certificate Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificate', to='certifications.certificaterequest'),
        ),
    ]
