# Generated by Django 6.0.2 on 2026-02-22 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('good_moral', 'Good Moral Certificate'), ('business_permit', 'Business Permit/Clearance'), ('comelec', 'COMELEC Certificate'), ('cedula', 'Community Tax Certificate'), ('late_registration', 'Certificate of Late Registration')], max_length=30)),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('purpose', models.TextField()),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('or_number', models.CharField(blank=True, max_length=50, verbose_name='OR Number')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-date_issued'],
            },
        ),
    ]
