# Generated by Django 6.0.4 on 2026-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_number', models.CharField(max_length=50, unique=True, verbose_name='CTC Number')),
                ('taxpayer_type', models.CharField(choices=[('individual', 'Individual'), ('corporation', 'Corporation')], default='individual', max_length=20)),
                ('place_of_issue', models.CharField(max_length=200)),
                ('height', models.CharField(blank=True, help_text='e.g. 170 cm', max_length=20)),
                ('weight', models.CharField(blank=True, help_text='e.g. 65 kg', max_length=20)),
                ('raw_taxable_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Property Value')),
                ('raw_taxable_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Gross Receipts')),
                ('raw_taxable_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Annual Income')),
                ('basic_tax', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('additional_tax_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Property)')),
                ('additional_tax_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Business)')),
                ('additional_tax_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Income)')),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cedula',
                'verbose_name_plural': 'Cedulas',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('good_moral', 'Good Moral Certificate'), ('business_permit', 'Business Permit/Clearance'), ('comelec', 'COMELEC Certificate'), ('cedula', 'Community Tax Certificate'), ('late_registration', 'Certificate of Late Registration')], max_length=30)),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('purpose', models.TextField()),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('child_name', models.CharField(blank=True, max_length=200)),
                ('child_birth_date', models.DateField(blank=True, null=True)),
                ('child_birth_place', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('or_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OR Number')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-date_issued', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('good_moral', 'Good Moral Certificate'), ('business_permit', 'Business Permit/Clearance'), ('comelec', 'COMELEC Certificate'), ('cedula', 'Community Tax Certificate'), ('late_registration', 'Certificate of Late Registration')], max_length=30)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_type', models.CharField(blank=True, max_length=200)),
                ('taxpayer_type', models.CharField(blank=True, max_length=20)),
                ('place_of_issue', models.CharField(blank=True, max_length=200)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('raw_taxable_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('raw_taxable_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('raw_taxable_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('child_name', models.CharField(blank=True, max_length=200)),
                ('child_birth_date', models.DateField(blank=True, null=True)),
                ('child_birth_place', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Admin notes (shown to resident on rejection)')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate Request',
                'verbose_name_plural': 'Certificate Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
