# Generated by Django 4.2.21 on 2026-06-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='is_first_time_jobseeker',
            field=models.BooleanField(default=False),
        ),
    ]
