# Generated by Django 6.0.2 on 2026-04-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_number', models.CharField(max_length=50, unique=True, verbose_name='CTC Number')),
                ('place_of_issue', models.CharField(max_length=200)),
                ('height', models.CharField(blank=True, help_text='e.g. 170 cm', max_length=20)),
                ('weight', models.CharField(blank=True, help_text='e.g. 65 kg', max_length=20)),
                ('basic_tax', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('additional_tax_property', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax on Real Property')),
                ('additional_tax_business', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax on Business')),
                ('additional_tax_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax on Profession/Income')),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_details', to='certifications.certificate')),
            ],
            options={
                'verbose_name': 'Cedula',
                'verbose_name_plural': 'Cedulas',
            },
        ),
    ]
