# Generated by Django 6.0.4 on 2026-05-03 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certifications', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='residents.resident'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_details', to='certifications.certificate'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_request', to='certifications.certificate'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cert_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='residents.resident'),
        ),
    ]
