# Generated by Django 4.2.21 on 2026-06-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0010_resident_parent_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certifications', '0002_certificaterequest_is_first_time_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='RA11261Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('declaration_confirmed', models.BooleanField()),
                ('uploaded_docs', models.FileField(upload_to='ra11261_docs/')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra11261_applications', to='residents.resident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirstTimeJobseekerRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('availed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('certificate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra11261_availments', to='certifications.certificaterequest')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ra11261_roster', to='residents.resident')),
            ],
            options={
                'ordering': ['-certification_date'],
            },
        ),
    ]
