# Generated by Django 6.0.2 on 2026-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedula',
            name='taxpayer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporation', 'Corporation')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='additional_tax_business',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax on Business / Gross Receipts'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='additional_tax_property',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax on Real Property / Assessed Value'),
        ),
    ]
