# Generated by Django 6.0.2 on 2026-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0003_cedula_taxpayer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedula',
            name='raw_taxable_business',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Gross Receipts'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='raw_taxable_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Annual Income'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='raw_taxable_property',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxable Property Value'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='additional_tax_business',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Business)'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='additional_tax_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Income)'),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='additional_tax_property',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Additional Tax (Property)'),
        ),
    ]
