# Generated by Django 6.0.2 on 2026-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_cedula_raw_taxable_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OR Number'),
        ),
    ]
