# Generated by Django 6.0.2 on 2026-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0006_alter_certificate_options_certificaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='business_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='raw_taxable_business',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='raw_taxable_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='raw_taxable_property',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='taxpayer_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
