# Generated by Django 6.0.2 on 2026-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0007_certificaterequest_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='child_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='child_birth_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='child_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='child_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='child_birth_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='child_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
