# Generated by Django 6.0.4 on 2026-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinance_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=200)),
                ('date_enacted', models.DateField()),
                ('date_effectivity', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('peace_order', 'Peace and Order'), ('health', 'Health and Sanitation'), ('environment', 'Environment'), ('revenue', 'Revenue and Finance'), ('infrastructure', 'Infrastructure'), ('social_welfare', 'Social Welfare'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('amended', 'Amended'), ('repealed', 'Repealed'), ('pending', 'Pending')], default='active', max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='ordinances/')),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordinance',
                'verbose_name_plural': 'Ordinances',
                'ordering': ['-date_enacted'],
            },
        ),
    ]
