# Generated by Django 4.2.21 on 2026-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinance',
            name='body_content',
            field=models.TextField(blank=True, help_text='Full text of the ordinance'),
        ),
        migrations.AddField(
            model_name='ordinance',
            name='signatories',
            field=models.TextField(blank=True, help_text='Signatories of the ordinance'),
        ),
    ]
