# Generated by Django 6.0.4 on 2026-05-03 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('captain', 'Punong Barangay (Captain)'), ('kagawad', 'Sangguniang Barangay Member (Kagawad)'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('sk_chairman', 'SK Chairperson'), ('sk_kagawad', 'SK Kagawad'), ('tanod', 'Barangay Tanod'), ('health_worker', 'Barangay Health Worker (BHW)'), ('nutrition_scholar', 'Barangay Nutrition Scholar (BNS)'), ('day_care_worker', 'Day Care Worker'), ('lupon', 'Lupon Member'), ('clerk', 'Barangay Clerk'), ('staff', 'Barangay Staff')], max_length=30)),
                ('committee', models.CharField(blank=True, help_text='Committee assignment', max_length=200)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fingerprint_template', models.TextField(blank=True, help_text='Base64 encoded fingerprint template', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_record', to='residents.resident')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Official',
                'verbose_name_plural': 'Officials',
                'ordering': ['position'],
            },
        ),
    ]
