# Generated by Django 6.0.4 on 2026-05-06 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('captain', 'Punong Barangay (Captain)'), ('kagawad', 'Sangguniang Barangay Member (Kagawad)'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('sk_chairman', 'SK Chairperson'), ('sk_kagawad', 'SK Kagawad'), ('tanod', 'Barangay Tanod'), ('health_worker', 'Barangay Health Worker (BHW)'), ('nutrition_scholar', 'Barangay Nutrition Scholar (BNS)'), ('day_care_worker', 'Day Care Worker'), ('lupon', 'Lupon Member'), ('clerk', 'Barangay Clerk'), ('staff', 'Barangay Staff')], max_length=30)),
                ('committee', models.CharField(blank=True, help_text='Committee assignment', max_length=200)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to soft-delete without losing records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_record', to='residents.resident')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Official',
                'verbose_name_plural': 'Officials',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='OfficialInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[('captain', 'Punong Barangay (Captain)'), ('kagawad', 'Sangguniang Barangay Member (Kagawad)'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('sk_chairman', 'SK Chairperson'), ('sk_kagawad', 'SK Kagawad'), ('tanod', 'Barangay Tanod'), ('health_worker', 'Barangay Health Worker (BHW)'), ('nutrition_scholar', 'Barangay Nutrition Scholar (BNS)'), ('day_care_worker', 'Day Care Worker'), ('lupon', 'Lupon Member'), ('clerk', 'Barangay Clerk'), ('staff', 'Barangay Staff')], max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('appointment_letter', models.FileField(blank=True, null=True, upload_to='official_docs/appointment/')),
                ('valid_id', models.FileField(blank=True, null=True, upload_to='official_docs/id/')),
                ('captain_approved', models.BooleanField(default=False)),
                ('secretary_approved', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_documents', 'Pending Documents'), ('pending_approval', 'Pending Approval'), ('pending_otp', 'Pending OTP'), ('activated', 'Activated'), ('rejected', 'Rejected')], default='pending_documents', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_official_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='officials.officialinvite')),
            ],
        ),
    ]
