# Generated by Django 4.2.21 on 2026-03-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='fingerprint_template',
            field=models.TextField(blank=True, help_text='Base64 encoded fingerprint template', null=True),
        ),
    ]
