# Generated by Django 4.2.21 on 2026-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.CharField(choices=[('captain', 'Punong Barangay (Captain)'), ('kagawad', 'Sangguniang Barangay Member (Kagawad)'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('sk_chairman', 'SK Chairperson'), ('sk_kagawad', 'SK Kagawad'), ('tanod', 'Barangay Tanod'), ('bhw', 'Barangay Health Worker (BHW)'), ('nutrition_scholar', 'Barangay Nutrition Scholar (BNS)'), ('day_care_worker', 'Day Care Worker'), ('lupon', 'Lupon Member'), ('clerk', 'Barangay Clerk'), ('staff', 'Barangay Staff')], max_length=30),
        ),
        migrations.AlterField(
            model_name='officialinvite',
            name='position',
            field=models.CharField(choices=[('captain', 'Punong Barangay (Captain)'), ('kagawad', 'Sangguniang Barangay Member (Kagawad)'), ('secretary', 'Barangay Secretary'), ('treasurer', 'Barangay Treasurer'), ('sk_chairman', 'SK Chairperson'), ('sk_kagawad', 'SK Kagawad'), ('tanod', 'Barangay Tanod'), ('bhw', 'Barangay Health Worker (BHW)'), ('nutrition_scholar', 'Barangay Nutrition Scholar (BNS)'), ('day_care_worker', 'Day Care Worker'), ('lupon', 'Lupon Member'), ('clerk', 'Barangay Clerk'), ('staff', 'Barangay Staff')], max_length=30),
        ),
    ]
