# Generated by Django 4.2.21 on 2026-05-09 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officials', '0002_alter_official_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
