# Generated by Django 6.0.4 on 2026-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_officialinvite_onboardingauditlog'),
    ]

    def nullify_biometrics(apps, schema_editor):
        Official = apps.get_model('officials', 'Official')
        Official.objects.all().update(fingerprint_template=None)

    operations = [
        migrations.RunPython(nullify_biometrics),
    ]
