# Generated by Django 4.2.21 on 2026-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_alter_official_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
