# Generated by Django 6.0.2 on 2026-02-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.TextField(help_text='JSON-encoded face encoding array')),
                ('photo', models.ImageField(upload_to='face_encodings/')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='officials.official')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('face', 'Face Recognition'), ('manual', 'Manual Entry'), ('biometric', 'Biometric/Fingerprint')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('photo_in', models.ImageField(blank=True, null=True, upload_to='attendance/photos/')),
                ('photo_out', models.ImageField(blank=True, null=True, upload_to='attendance/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='officials.official')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-date', 'official'],
                'unique_together': {('official', 'date')},
            },
        ),
    ]
