# Generated by Django 4.2.21 on 2026-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, unique=True)),
                ('am_in', models.TimeField(default='08:00')),
                ('am_out', models.TimeField(default='12:00')),
                ('pm_in', models.TimeField(default='13:00')),
                ('pm_out', models.TimeField(default='17:00')),
                ('is_day_off', models.BooleanField(default=False)),
                ('grace_period', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift Configuration',
                'verbose_name_plural': 'Shift Configurations',
            },
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='am_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='am_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='pm_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='pm_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
