# Generated by Django 6.0.4 on 2026-05-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='officials.official'),
        ),
        migrations.AddField(
            model_name='faceencoding',
            name='official',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='officials.official'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('official', 'date')},
        ),
    ]
