# Generated by Django 4.2.21 on 2026-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_shiftconfiguration_attendancelog_am_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_day_off', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Date',
                'verbose_name_plural': 'Special Dates',
                'ordering': ['-date'],
            },
        ),
    ]
