# Generated by Django 4.2.21 on 2026-05-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_alter_official_user'),
        ('attendance', '0003_specialdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('regular', 'Regular (8 AM - 5 PM)'), ('morning', 'Morning Shift (8 AM - 12 PM)'), ('afternoon', 'Afternoon Shift (1 PM - 5 PM)'), ('night', 'Night Shift (10 PM - 6 AM)'), ('day_off', 'Day Off / Rest Day'), ('leave', 'On Leave')], default='regular', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, help_text='Reason for leave, extra info, etc.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='officials.official')),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'ordering': ['date', 'official'],
                'unique_together': {('official', 'date')},
            },
        ),
    ]
